# Generated by Django 5.2.5 on 2025-08-26 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'état',
                'verbose_name_plural': 'états',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'localisation',
                'verbose_name_plural': 'localisations',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='produit',
            name='reference_modele',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='magasin.categorie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='etat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='magasin.etat'),
        ),
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='produit',
            name='localisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='magasin.localisation'),
        ),
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together={('nom', 'categorie', 'localisation')},
        ),
    ]
